version: "3"
services:
  backend:
    image: guriaa/docker-backend
    ports:
      - "5000:5000" # adjust based on backend app port
  frontend:
    image: guriaa/docker-frontend
    environment:
      - BACKEND_URL=http://backend:5000/submit
    ports:
      - "3000:3000" # adjust based on frontend app port
    depends_on:
      - backend
