version: "3.8"

services:
  backend:
    build: backend
    hostname: backend-host
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    networks:
      - Docker-network

  frontend:
    build: frontend
    hostname: frontend-host
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_URL=http://backend-host:5000/submit
    ports:
      - "3000:3000"
    links:
      - backend
    depends_on:
      - backend
    networks:
      - Docker-network

networks:
  Docker-network: {}
